// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLoaNKQMJdxEGnMFwHUaxWTTSw99sihrQ',
    appId: '1:942723313652:web:222b6f3bbe19a1f5b093a1',
    messagingSenderId: '942723313652',
    projectId: 'gannar-a92de',
    authDomain: 'gannar-a92de.firebaseapp.com',
    storageBucket: 'gannar-a92de.appspot.com',
    measurementId: 'G-068N4540LF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNSH-QJtbZ9CaPuByETXuxBVpX_Rvbd50',
    appId: '1:942723313652:android:5cb5b4beb8031975b093a1',
    messagingSenderId: '942723313652',
    projectId: 'gannar-a92de',
    storageBucket: 'gannar-a92de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwyR3hC1v0ePzN0zpyoXcftTtKbeUpy0E',
    appId: '1:942723313652:ios:cf3af688553f617db093a1',
    messagingSenderId: '942723313652',
    projectId: 'gannar-a92de',
    storageBucket: 'gannar-a92de.appspot.com',
    iosBundleId: 'com.example.gannar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwyR3hC1v0ePzN0zpyoXcftTtKbeUpy0E',
    appId: '1:942723313652:ios:3ca4ca09d68f86f1b093a1',
    messagingSenderId: '942723313652',
    projectId: 'gannar-a92de',
    storageBucket: 'gannar-a92de.appspot.com',
    iosBundleId: 'com.example.gannar.RunnerTests',
  );
}
